---
title: "Resultats"
output: html_notebook
---

```{r}
setwd(".")
filename = "uo_nn_batch_425924225-223314308.csv"
data = read.csv(filename, header = T, sep = ";")
head(data)
```

Passem les variables la i isd a factors

```{r}
#data$la = as.factor(data$la)
#data$isd = as.factor(data$isd)
# data$num_target = as.factor(data$num_target)
```

fem uns plotitos

```{r}
boxplot.33 = function(data, variable) {
  par(mfrow=c(3,3))
  boxplot(variable[data$isd==1 & data$la==0])
  boxplot(variable[data$isd==1 & data$la==1])
  boxplot(variable[data$isd==1 & data$la==10])

  boxplot(variable[data$isd==3 & data$la==0])
  boxplot(variable[data$isd==3 & data$la==1])
  boxplot(variable[data$isd==3 & data$la==10])

  boxplot(variable[data$isd==4 & data$la==0])
  boxplot(variable[data$isd==4 & data$la==1])
  boxplot(variable[data$isd==4 & data$la==10])
  }
```


```{r}
boxplot.33(data, data$L.)

```

```{r}
col.func = function(i) {
  if (i == 1) return("firebrick")
  else if (i == 3) return("red4")
  else return("blue")
}

points.func = function(i) {
  if (i == 1) return(2)
  else if (i == 3) return(0)
  else return(3)
}
```

### Convergence

```{r}
for (lambda in c(0, 1, 10)) {
  main.t = c("lambda = 0","lambda = 1", "", "", "", "", "", "", "", "","lambda = 10")
  plot(c(0,9), c(max(data$L.[data$la==lambda])*1.1, min(data$L.[data$la==lambda])), ty="n", xlab="num target", ylab = "L*", main = main.t[lambda+1])
  legend(0, max(data$L.[data$la==lambda])*1.1, c("GM", "QNM", "SGM"), col = c("firebrick", "red4", "blue"), pch= 19)
  for (sd in c(1, 3, 7))
    lines(sort(data$num_target[data$isd==sd & data$la==lambda]), data$L.[data$isd==sd & data$la==lambda], ty="b", col = col.func(sd), pch= points.func(sd))
}
```

```{r}
for (lambda in c(0, 1, 10)) {
  main.t = c("lambda = 0","lambda = 1", "", "", "", "", "", "", "", "","lambda = 10")
  plot(c(0,9), c(max(data$niter[data$la==lambda])*1.1, min(data$niter[data$la==lambda])), ty="n", xlab="num target", ylab = "niter", main = main.t[lambda+1])
  legend(0, max(data$niter[data$la==lambda])*1.1, c("GM", "QNM", "SGM"), col = c("firebrick", "red4", "blue"), pch= 19)
  for (sd in c(1, 3, 7))
    lines(sort(data$num_target[data$isd==sd & data$la==lambda]), data$niter[data$isd==sd & data$la==lambda], ty="b", col = col.func(sd), pch= points.func(sd))
}
```


```{r}
for (lambda in c(0, 1, 10)) {
  main.t = c("lambda = 0","lambda = 1", "", "", "", "", "", "", "", "","lambda = 10")
  plot(c(0,9), c(max(data$tex[data$la==lambda])*1.1, min(data$tex[data$la==lambda])), ty="n", xlab="num target", ylab = "tex", main = main.t[lambda+1])
  legend(0, max(data$tex[data$la==lambda])*1.1, c("GM", "QNM", "SGM"), col = c("firebrick", "red4", "blue"), pch= 19)
  for (sd in c(1, 3, 7))
    lines(sort(data$num_target[data$isd==sd & data$la==lambda]), data$tex[data$isd==sd & data$la==lambda], ty="b", col = col.func(sd), pch= points.func(sd))
}
```

```{r}
for (lambda in c(0, 1, 10)) {
  data$y = data$tex / data$niter
  main.t = c("lambda = 0","lambda = 1", "", "", "", "", "", "", "", "","lambda = 10")
  plot(c(0,9), c(max(data$y[data$la==lambda])*1.5, min(data$y[data$la==lambda])), ty="n", xlab="num target", ylab = "tex/niter", main = main.t[lambda+1])
  legend(0, max(data$y[data$la==lambda])*1.5, c("GM", "QNM", "SGM"), col = c("firebrick", "red4", "blue"), pch= 19)
  for (sd in c(1, 3, 7))
    lines(sort(data$num_target[data$isd==sd & data$la==lambda]), data$y[data$isd==sd & data$la==lambda], ty="b", col = col.func(sd), pch= points.func(sd))
}
```

### Accuracy

```{r}
targets = c(0:9)
avg.acc.tar = c(0:9)
for (i in avg.acc.tar) {
  acc = mean(data$te_acc[data$num_target == i])
  avg.acc.tar[i+1] = acc
}



plot(data$num_target, data$te_acc, xlab="", ylab="", main="")
lines(targets, avg.acc.tar)
# boxplot(data$te_acc ~ data$num_target, add=T)
```

```{r}
boxplot(data$te_acc ~ data$num_target, add=T)
```

